### ISSUE TITLE
Export/Import keys and use them with OpenSSL and similiar 

### ISSUE THREAD

**Issue by habakuk007** [dnauck/Portable.Licensing#13]
Hello Daniel,

I try to export the keys that are generated by Portable.Licensing or to import keys that were generated with OpenSSL, but only get cryptic error messages. Do you have a hint how I can do this?

I want to issue licenses with a web application that doesn't run under asp.net

Thanks for your help!
   Stefan

**Comment by dnauck** [comment]
Hello,

i'm using BouncyCastle.NET to create keys and manage encryption. Its a port of the famous Java lib BouncyCastle. I don't know if its compatible with OpenSSL.

All code that has todo with it is in this namespace: https://github.com/dnauck/Portable.Licensing/tree/develop/src/Portable.Licensing/Security/Cryptography

Maybe you want to open a new topic at their forums/mailing list/github issue tracker with some more details about how you do it with OpenSSL.

Another idea would be to write a small console app that is using Portable.Licensing and precompile it/use mkbundle to make it a real unix app and call it from your web application.

**Comment by habakuk007** [comment]
Thanks for your idea with mkbundle - it didn't work to use it on different machines (with different linux versions) because it still depends on libs that had different versions. 

But then I used mono directly to run the "wrapper executable" (mono 3.12.0 or newer is needed for full PCL support) and that worked.
