### ISSUE TITLE
Reference issue with xml.linq.dll

### ISSUE THREAD

**Issue by codeonnn** [dnauck/Portable.Licensing#18]
I had used 1.0 version in Win Forms project. Every thing worked on my machine.
But once I deployed application on my customer machine. Portable.Licensing started giving below  errors.

Here reference to System.xml.linq.dll is added from Silverlight installation folder. Those machine doesen't have it installed it will fail there. It worked on my machine as I have it installed.

This reference should be added from  : 

C:\Program Files\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\System.Xml.Linq.dll

Curenlty it is -
Assembly Location - C:\Program Files\Microsoft SDKs\Silverlight\v4.0\Libraries\Client\System.Xml.Linq.dll

Assembly name - System.Xml.Linq, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Platform - Silverlight v4.0

System.IO.FileLoadException: Could not load file or assembly 'System.Xml.Linq, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
File name: 'System.Xml.Linq, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Retargetable=Yes'
   at Portable.Licensing.License.Load(String xmlString)

**Comment by dnauck** [comment]
Hi,

the the other issue with the type load exception (on the old site) related?

**Comment by codeonnn** [comment]
Actually I fixed this one, by removing portable ness from portable.licensing.dll Added reference to .net 4.0 dll's and above mentioned issue got resolved. I only need it on Winforms. 

Then I started getting the other exception mentioned on old site.

**Comment by codeonnn** [comment]
This issue gets resolved, once the user installs patch released by MS for resolving assemblies with Portable Licensing. 

http://www.microsoft.com/en-in/download/details.aspx?id=3556
