### ISSUE TITLE
License.Expiration - Millisecond part is ignored

### ISSUE THREAD

**Issue by makcakaya** [dnauck/Portable.Licensing#19]
Hi Daniel;

I have problem when testing expiration date with milliseconds. I know, no one will ever need to use milliseconds to set an expiration date but the issue makes writing tests hard.

Test code is below:

```
[Fact]
        public void Expiration()
        {
            var passPhrase = "TopSecretPhrase";
            var keyGen = KeyGenerator.Create();
            var keyPair = keyGen.GenerateKeyPair();
            var privateKey = keyPair.ToEncryptedPrivateKeyString(passPhrase);

            var dateNoMs = DateTime.Parse("01.01.2015");
            var licenseNoMs = License.New().ExpiresAt(dateNoMs).CreateAndSignWithPrivateKey(privateKey, passPhrase);
            Assert.Equal(dateNoMs, licenseNoMs.Expiration); // Cool, no problem.

            var dateWithMs = DateTime.Now; // Has milliseconds
            var licenseWithMs = License.New().ExpiresAt(dateWithMs).CreateAndSignWithPrivateKey(privateKey, passPhrase);
            Assert.Equal(dateWithMs, licenseWithMs.Expiration); // Fails
            // Expected: 2015-05-08T17:43:51.9035841+03:00
            // Actual:   2015-05-08T17:43:51.0000000+03:00
        }
```

Using `DateTimeStyles.RoundtripKind` enum seems to solve the issue but the [MSDN](https://msdn.microsoft.com/en-us/library/91hfhz89%28v=vs.110%29.aspx) says it cannot be used with `DateTimeStyles.AssumeUniversal`.

**Comment by dnauck** [comment]
If you just want to test you could also use DateTime.Now.Date that does not have time information.

Is there any use case other then using DateTime.Now during Testing?

What is your real use case? Maybe we can find a nice solution for it.

**Comment by makcakaya** [comment]
Yeah, using DateTime.Date is a good option.

I was just surprised when I did serialization-deserialization and the Expiration's did not match.

**Comment by dnauck** [comment]
Can we close this issue?

**Comment by makcakaya** [comment]
Yes.
