### ISSUE TITLE
Validation messages are not localizable

### ISSUE THREAD

**Issue by makcakaya** [dnauck/Portable.Licensing#23]
For example, the message "Licensing for this product has expired!" is not appropriate if the application targets a different language.

Maybe validation should return an enumeration and we should use some kind of dictionary to get the message, and how to resolve information.

**Comment by makcakaya** [comment]
Change the title to more meaningful

**Comment by dnauck** [comment]
Portable.Licensing has only default english locale strings. It has only two pre defined validation failures:
- LicenseExpiredValidationFailure
- InvalidSignatureValidationFailure

Both provide default english texts; but you can easily match their type and display your own localized text in your UI. I don't know why we need an extra enum here.

Maybe you can elaborate a bit more, please.

**Comment by makcakaya** [comment]
Hmm, so we should utilize the type like this:

``` C#
var failures = _license.Validate().ExpirationDate().And().Signature(publicKey).AssertValidLicense();
foreach(var failure in failures)
{
    if(failure is LicenseExpiredValidationFailure){ .... }
    else if (failure is InvalidSignatureValidationFailure) {.....}
    else if (failure is GeneralValidationFailure) {..... } // general validation failure
    else { throw InvalidOperationException("Should not happen"); }
}
```

This solves my problem.
