### ISSUE TITLE
The input is not a valid Base-64

### ISSUE THREAD

**Issue by m-hcz** [dnauck/Portable.Licensing#58]
Hi, could u help me with this error "'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters"?

License was generated by Portable.Licensing 1.1.0 in .NET 7 console app and validation was by Portable.Licensing 1.1.0 in WPF app .NET 4.8.

![image](https://github.com/dnauck/Portable.Licensing/assets/72664968/aa5dd795-8e7e-4bf4-9b58-8d8b47d56e64)

**Comment by Shahabs2004** [comment]
I had the same problem. Until I realized that instead of using the file content, I passed the file name to the function. Make sure that the file content is read correctly(i mean public key File). Read publickey File into a reachtextbox to Check it

**Comment by Shahabs2004** [comment]
var publicKey = File.ReadAllText("publicKey.pem");
            var Testlicense = Portable.Licensing.License.Load(File.ReadAllText("license.lic"));
            var validationFailures = Testlicense.Validate()
                                    .ExpirationDate()
            .When(lic => lic.Type == LicenseType.Trial)
                                    .And()
                                    .Signature(publicKey)
                                    .AssertValidLicense();

**Comment by m-hcz** [comment]
thanks for help :)
